import { Course, DesignTokens } from "./types";

export const T: DesignTokens = {
  teal: "#2dd4bf",
  tealDim: "#0d9488",
  tealBg: "rgba(45,212,191,0.08)",
  tealBorder: "rgba(45,212,191,0.22)",
  grey: "#64748b",
  greyLight: "#94a3b8",
  greyDark: "#334155",
  greyBg: "rgba(100,116,139,0.08)",
  slate: "#1e293b",
  ink: "#060b18",
  surface: "rgba(12,18,36,0.85)",
  orange: "#fb923c",
  purple: "#818cf8",
  green: "#4ade80",
  red: "#f87171",
  yellow: "#facc15",
  blue: "#38bdf8",
  pink: "#f472b6",
};

export const GLOBAL_STYLES = `
  @import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,600;12..96,700;12..96,800&family=JetBrains+Mono:wght@400;600;700&family=Onest:wght@400;500;600&display=swap');
  @keyframes pulse { 0%,100%{opacity:1;box-shadow:0 0 6px currentColor}50%{opacity:.5;box-shadow:none} }
  @keyframes float { 0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)} }
  @keyframes fadeUp { from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)} }
  @keyframes slideIn { from{opacity:0;transform:translateX(10px)}to{opacity:1;transform:translateX(0)} }
  @keyframes popIn { from{opacity:0;transform:scale(0.92)}to{opacity:1;transform:scale(1)} }
  @keyframes flow { 0%{stroke-dashoffset:100}100%{stroke-dashoffset:0} }
  * { box-sizing:border-box; }
  ::-webkit-scrollbar{width:4px} ::-webkit-scrollbar-track{background:transparent}
  ::-webkit-scrollbar-thumb{background:#1e293b;border-radius:4px}
`;

export const COURSES: Course[] = [
  {
    id: "fundamentals",
    num: "01",
    title: "dbt Fundamentals",
    subtitle: "Modeling, sources, tests & docs",
    icon: "🏗️",
    color: T.purple,
    difficulty: "Beginner",
    duration: "45 min",
    topics: [
      "Warehouse connection",
      "Project structure",
      "Modeling",
      "Sources",
      "Testing",
      "Documentation",
      "Deployment",
    ],
  },
  {
    id: "jinja",
    num: "02",
    title: "Jinja, Macros & Packages",
    subtitle: "Extend dbt with dynamic SQL",
    icon: "🧩",
    color: T.pink,
    difficulty: "Intermediate",
    duration: "35 min",
    topics: [
      "Jinja templating",
      "ref() & source()",
      "Custom macros",
      "dbt-utils",
      "Packages",
    ],
  },
  {
    id: "incremental",
    num: "03",
    title: "Incremental Models",
    subtitle: "Process only new or changed data",
    icon: "🧱",
    color: T.orange,
    difficulty: "Intermediate",
    duration: "40 min",
    topics: [
      "Full refresh vs incremental",
      "is_incremental()",
      "Strategies",
      "Schema changes",
      "Warehouse strategies",
    ],
    fullyBuilt: true,
  },
  {
    id: "snapshots",
    num: "04",
    title: "Snapshots",
    subtitle: "Track historical records over time",
    icon: "📸",
    color: T.teal,
    difficulty: "Intermediate",
    duration: "30 min",
    topics: [
      "SCD Type 2",
      "dbt_valid_from/to",
      "check strategy",
      "timestamp strategy",
      "History queries",
    ],
  },
  {
    id: "seeds",
    num: "05",
    title: "Analyses & Seeds",
    subtitle: "Ad hoc queries and CSV data",
    icon: "🌱",
    color: "#a3e635",
    difficulty: "Beginner",
    duration: "20 min",
    topics: [
      "Seeds overview",
      "CSV versioning",
      "Analyses",
      "Ad hoc queries",
      "ref() in analyses",
    ],
  },
  {
    id: "exposures",
    num: "06",
    title: "Exposures",
    subtitle: "Downstream dependency visibility",
    icon: "🔭",
    color: T.blue,
    difficulty: "Beginner",
    duration: "20 min",
    topics: [
      "Exposure config",
      "YAML definition",
      "DAG visibility",
      "Dependency tracking",
      "Freshness",
    ],
  },
  {
    id: "state",
    num: "07",
    title: "State Management",
    subtitle: "Run only what changed",
    icon: "⚡",
    color: T.yellow,
    difficulty: "Advanced",
    duration: "25 min",
    topics: [
      "dbt state",
      "Slim CI",
      "modified selector",
      "Artifacts",
      "Deferred runs",
    ],
  },
  {
    id: "retry",
    num: "08",
    title: "dbt Retry",
    subtitle: "Efficiently rebuild failed pipelines",
    icon: "🔁",
    color: T.orange,
    difficulty: "Beginner",
    duration: "15 min",
    topics: [
      "dbt retry command",
      "run_results.json",
      "Error recovery",
      "CI patterns",
      "Best practices",
    ],
  },
  {
    id: "mesh",
    num: "09",
    title: "dbt Mesh",
    subtitle: "Cross-project data products at scale",
    icon: "🕸️",
    color: "#c084fc",
    difficulty: "Advanced",
    duration: "40 min",
    topics: [
      "Projects & contracts",
      "Public models",
      "Cross-project refs",
      "Governance",
      "Producer/consumer",
    ],
  },
  {
    id: "testing",
    num: "10",
    title: "Advanced Testing",
    subtitle: "Custom tests, packages & config",
    icon: "🧪",
    color: T.teal,
    difficulty: "Advanced",
    duration: "35 min",
    topics: [
      "Generic tests",
      "Custom tests",
      "dbt-expectations",
      "Test severity",
      "Test configs",
    ],
  },
  {
    id: "deployment",
    num: "11",
    title: "Advanced Deployment",
    subtitle: "CI, orchestration & environments",
    icon: "🚀",
    color: T.red,
    difficulty: "Advanced",
    duration: "35 min",
    topics: [
      "Continuous integration",
      "Conflicting jobs",
      "Environment configs",
      "dbt Cloud jobs",
      "Slim CI",
    ],
  },
  {
    id: "clone",
    num: "12",
    title: "dbt Clone",
    subtitle: "Zero-copy dev & test environments",
    icon: "🪞",
    color: "#67e8f9",
    difficulty: "Intermediate",
    duration: "20 min",
    topics: [
      "dbt clone command",
      "Zero-copy cloning",
      "Warehouse clones",
      "Dev workflows",
      "Cost savings",
    ],
  },
  {
    id: "grants",
    num: "13",
    title: "Grants",
    subtitle: "Fine-grained permission control",
    icon: "🔐",
    color: "#86efac",
    difficulty: "Intermediate",
    duration: "20 min",
    topics: [
      "Grant config",
      "Models & seeds",
      "Snapshots grants",
      "Role-based access",
      "Auto-grants",
    ],
  },
  {
    id: "python",
    num: "14",
    title: "Python dbt Models",
    subtitle: "ML & statistics beyond SQL",
    icon: "🐍",
    color: T.yellow,
    difficulty: "Advanced",
    duration: "35 min",
    topics: [
      "Python models",
      "Pandas & PySpark",
      "ML use cases",
      "SQL + Python hybrid",
      "Packages",
    ],
  },
];

export const DIFF_COLOR: Record<string, string> = {
  Beginner: T.green,
  Intermediate: T.orange,
  Advanced: T.red,
};
